// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GETBIN
arma::vec GETBIN(arma::vec PVEC);
RcppExport SEXP _Phase12Compare_GETBIN(SEXP PVECSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type PVEC(PVECSEXP);
    rcpp_result_gen = Rcpp::wrap(GETBIN(PVEC));
    return rcpp_result_gen;
END_RCPP
}
// ReturnOpt
int ReturnOpt(arma::vec Desire, arma::vec DoseTried);
RcppExport SEXP _Phase12Compare_ReturnOpt(SEXP DesireSEXP, SEXP DoseTriedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Desire(DesireSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type DoseTried(DoseTriedSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnOpt(Desire, DoseTried));
    return rcpp_result_gen;
END_RCPP
}
// GetDesire
double GetDesire(double PE, double PT, arma::vec Contour);
RcppExport SEXP _Phase12Compare_GetDesire(SEXP PESEXP, SEXP PTSEXP, SEXP ContourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type PE(PESEXP);
    Rcpp::traits::input_parameter< double >::type PT(PTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Contour(ContourSEXP);
    rcpp_result_gen = Rcpp::wrap(GetDesire(PE, PT, Contour));
    return rcpp_result_gen;
END_RCPP
}
// RunAdaptiveEffToxTrialCORR
List RunAdaptiveEffToxTrialCORR(int DoseStart, arma::vec Dose, arma::vec Hypermeans, arma::vec Hypervars, arma::mat UT, arma::vec PiLim, arma::vec ProbLim, int cohort, int NET, int NF, double B, int nSims, arma::mat PMAT);
RcppExport SEXP _Phase12Compare_RunAdaptiveEffToxTrialCORR(SEXP DoseStartSEXP, SEXP DoseSEXP, SEXP HypermeansSEXP, SEXP HypervarsSEXP, SEXP UTSEXP, SEXP PiLimSEXP, SEXP ProbLimSEXP, SEXP cohortSEXP, SEXP NETSEXP, SEXP NFSEXP, SEXP BSEXP, SEXP nSimsSEXP, SEXP PMATSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type DoseStart(DoseStartSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypermeans(HypermeansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypervars(HypervarsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type UT(UTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type PiLim(PiLimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ProbLim(ProbLimSEXP);
    Rcpp::traits::input_parameter< int >::type cohort(cohortSEXP);
    Rcpp::traits::input_parameter< int >::type NET(NETSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type PMAT(PMATSEXP);
    rcpp_result_gen = Rcpp::wrap(RunAdaptiveEffToxTrialCORR(DoseStart, Dose, Hypermeans, Hypervars, UT, PiLim, ProbLim, cohort, NET, NF, B, nSims, PMAT));
    return rcpp_result_gen;
END_RCPP
}
// RunAdaptiveEffToxTrialCORRCONTOUR
List RunAdaptiveEffToxTrialCORRCONTOUR(int DoseStart, arma::vec Dose, arma::vec Hypermeans, arma::vec Hypervars, arma::vec Contour, arma::vec PiLim, arma::vec ProbLim, int cohort, int NET, int NF, double B, int nSims, arma::mat PMAT);
RcppExport SEXP _Phase12Compare_RunAdaptiveEffToxTrialCORRCONTOUR(SEXP DoseStartSEXP, SEXP DoseSEXP, SEXP HypermeansSEXP, SEXP HypervarsSEXP, SEXP ContourSEXP, SEXP PiLimSEXP, SEXP ProbLimSEXP, SEXP cohortSEXP, SEXP NETSEXP, SEXP NFSEXP, SEXP BSEXP, SEXP nSimsSEXP, SEXP PMATSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type DoseStart(DoseStartSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypermeans(HypermeansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypervars(HypervarsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Contour(ContourSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type PiLim(PiLimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ProbLim(ProbLimSEXP);
    Rcpp::traits::input_parameter< int >::type cohort(cohortSEXP);
    Rcpp::traits::input_parameter< int >::type NET(NETSEXP);
    Rcpp::traits::input_parameter< int >::type NF(NFSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type PMAT(PMATSEXP);
    rcpp_result_gen = Rcpp::wrap(RunAdaptiveEffToxTrialCORRCONTOUR(DoseStart, Dose, Hypermeans, Hypervars, Contour, PiLim, ProbLim, cohort, NET, NF, B, nSims, PMAT));
    return rcpp_result_gen;
END_RCPP
}
// UTEFFTOX
List UTEFFTOX(arma::vec YE, arma::vec YT, arma::vec Doses, arma::vec HypermeansEFF, arma::vec HypermeansTOX, arma::vec Hypervars, double B);
RcppExport SEXP _Phase12Compare_UTEFFTOX(SEXP YESEXP, SEXP YTSEXP, SEXP DosesSEXP, SEXP HypermeansEFFSEXP, SEXP HypermeansTOXSEXP, SEXP HypervarsSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type YE(YESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type YT(YTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Doses(DosesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type HypermeansEFF(HypermeansEFFSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type HypermeansTOX(HypermeansTOXSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypervars(HypervarsSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(UTEFFTOX(YE, YT, Doses, HypermeansEFF, HypermeansTOX, Hypervars, B));
    return rcpp_result_gen;
END_RCPP
}
// AssignEffTox
List AssignEffTox(arma::vec YE, arma::vec YT, arma::vec Doses, arma::vec Dose, arma::vec DosesTried, arma::vec Hypermeans, arma::vec Hypervars, arma::vec Contour, arma::vec PiLim, arma::vec ProbLim, double B);
RcppExport SEXP _Phase12Compare_AssignEffTox(SEXP YESEXP, SEXP YTSEXP, SEXP DosesSEXP, SEXP DoseSEXP, SEXP DosesTriedSEXP, SEXP HypermeansSEXP, SEXP HypervarsSEXP, SEXP ContourSEXP, SEXP PiLimSEXP, SEXP ProbLimSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type YE(YESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type YT(YTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Doses(DosesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type DosesTried(DosesTriedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypermeans(HypermeansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypervars(HypervarsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Contour(ContourSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type PiLim(PiLimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ProbLim(ProbLimSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(AssignEffTox(YE, YT, Doses, Dose, DosesTried, Hypermeans, Hypervars, Contour, PiLim, ProbLim, B));
    return rcpp_result_gen;
END_RCPP
}
// AssignEffToxUT
List AssignEffToxUT(arma::vec YE, arma::vec YT, arma::vec Doses, arma::vec Dose, arma::vec DosesTried, arma::vec Hypermeans, arma::vec Hypervars, arma::mat UT, arma::vec PiLim, arma::vec ProbLim, double B);
RcppExport SEXP _Phase12Compare_AssignEffToxUT(SEXP YESEXP, SEXP YTSEXP, SEXP DosesSEXP, SEXP DoseSEXP, SEXP DosesTriedSEXP, SEXP HypermeansSEXP, SEXP HypervarsSEXP, SEXP UTSEXP, SEXP PiLimSEXP, SEXP ProbLimSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type YE(YESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type YT(YTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Doses(DosesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type DosesTried(DosesTriedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypermeans(HypermeansSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Hypervars(HypervarsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type UT(UTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type PiLim(PiLimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ProbLim(ProbLimSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(AssignEffToxUT(YE, YT, Doses, Dose, DosesTried, Hypermeans, Hypervars, UT, PiLim, ProbLim, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Phase12Compare_GETBIN", (DL_FUNC) &_Phase12Compare_GETBIN, 1},
    {"_Phase12Compare_ReturnOpt", (DL_FUNC) &_Phase12Compare_ReturnOpt, 2},
    {"_Phase12Compare_GetDesire", (DL_FUNC) &_Phase12Compare_GetDesire, 3},
    {"_Phase12Compare_RunAdaptiveEffToxTrialCORR", (DL_FUNC) &_Phase12Compare_RunAdaptiveEffToxTrialCORR, 13},
    {"_Phase12Compare_RunAdaptiveEffToxTrialCORRCONTOUR", (DL_FUNC) &_Phase12Compare_RunAdaptiveEffToxTrialCORRCONTOUR, 13},
    {"_Phase12Compare_UTEFFTOX", (DL_FUNC) &_Phase12Compare_UTEFFTOX, 7},
    {"_Phase12Compare_AssignEffTox", (DL_FUNC) &_Phase12Compare_AssignEffTox, 11},
    {"_Phase12Compare_AssignEffToxUT", (DL_FUNC) &_Phase12Compare_AssignEffToxUT, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_Phase12Compare(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
